export interface UserType {
    id: Number;
    is_superuser: Boolean;
    first_name: String;
    last_name: String;
    email: String;
    is_staff: Boolean;
    date_joined: Date;
    username: String;
    role: Number;
    is_active: Boolean;
    is_locked: Boolean;
    is_logged_in: Boolean;
    date_added: Date;
    date_deleted?: Date;
    failed_login_attempts: Number;
    last_login: Date;
    old_password: String;
    date_password_changed?: Date;
    employee_number: Number;
    groups: Array<Number>;
    user_permissions: Array<Number>;
};


export interface EmployeeDetailsType {
    id: Number;
    employee_image?: String;
    emp_no: Number;
    first_name: String;
    middle_name?: String;
    last_name: String;
    suffix?: String;
    birthdate: Date;
    birth_place?: String;
    civil_status: String;
    gender: String;
    address: String;
    provincial_address?: String;
    mobile_phone: String;
    email_address?: String;
    date_hired: Date;
    date_resigned?: Date;
    approver: Number;
    date_added: Date;
    date_deleted?: Date;
    philhealth_code?: String;
    bio_id?: String;
    branch_code?: String;
    department_code?: String;
    division_code?: String;
    payroll_group_code?: String;
    position_code?: String;
    rank_code?: String;
    tax_code?: String;
    city_code?: String;
    pagibig_code?: String;
    sssid_code?: String;
};


export interface GetEmployeesListsType {
    id: Number;
    employee_image?: String;
    emp_no: Number;
    first_name: String;
    middle_name?: String;
    last_name: String;
    suffix?: String;
    birthdate: Date;
    birth_place?: String;
    civil_status: String;
    gender: String;
    address: String;
    provincial_address?: String;
    mobile_phone: String;
    email_address?: String;
    date_hired: Date;
    date_resigned?: Date;
    approver: Number;
    date_added: Date;
    date_deleted?: Date;
    philhealth_code?: String;
    bio_id?: String;
    branch_code?: String;
    department_code?: String;
    division_code?: String;
    payroll_group_code?: String;
    position_code?: String;
    rank_code?: String;
    tax_code?: String;
    city_code?: String;
    pagibig_code?: String;
    sssid_code?: String;
    user?: {
        is_superuser: Boolean;
        username: String;
        role: Number;
        is_active: Boolean;
        is_logged_in: Boolean;
        is_locked: Boolean;
        failed_login_attempts: Number;
        last_login: Date;
        old_password: String;
        date_password_changed?: Date; 
        date_added: Date;
        date_deleted?: Date;
        emp_no: Number;
        groups: Array<String>;
        user_permissions: Array<String>;
    }
};