import {
  HomeIcon,
  UserCircleIcon,
  TableCellsIcon,
  BellIcon,
  ArrowRightOnRectangleIcon,
  UserPlusIcon,
  HeartIcon,
  DocumentIcon,
  SpeakerWaveIcon,
  QuestionMarkCircleIcon
} from "@heroicons/react/24/solid";
import { Home, Profile, Tables, Notifications } from "@/pages/dashboard";
import { SignIn, SignUp } from "@/pages/auth";
import { IRoute } from "./types";

const icon = {
  className: "w-5 h-5 text-inherit",
};

export const routes: Array<IRoute> = [
  {
    id: 1000,
    layout: "dashboard",
    pages: [
      {
        id: 1100,
        icon: <HomeIcon {...icon} />,
        name: "dashboard",
        path: "/home",
        element: <Home />,
        hasSubItems: false,
      },
      {
        id: 1200,
        icon: <UserCircleIcon {...icon} />,
        name: "Employee",
        path: "/profile",
        element: <Profile />,
        hasSubItems: true,
        subItems: [
          {
            id: 1210,
            icon: <UserCircleIcon {...icon} />,
            name: "201 Files",
            path: "/employee/201-files",
            element: <Profile />,
            hasSubItems: false,
          },
          {
            id: 1220,
            icon: <UserCircleIcon {...icon} />,
            name: "Appraisal",
            path: "/employee/appraisal",
            element: <Profile />,
            hasSubItems: false,
          },
        ]
      },
      {
        id: 1300,
        icon: <TableCellsIcon {...icon} />,
        name: "DTR",
        path: "/tables",
        element: <Tables />,
        hasSubItems: true,
        subItems: [
          {
            id: 1310,
            icon: <TableCellsIcon {...icon} />,
            name: "Scheduler",
            path: "/tables/scheduler",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1320,
            icon: <TableCellsIcon {...icon} />,
            name: "Timekeeping",
            path: "/tables/timekeeping",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1330,
            icon: <TableCellsIcon {...icon} />,
            name: "Biometrics Data",
            path: "/tables/biometrics-data",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1340,
            icon: <TableCellsIcon {...icon} />,
            name: "DTR Summary",
            path: "/tables/dtr-summary",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1350,
            icon: <TableCellsIcon {...icon} />,
            name: "Leaves",
            path: "/tables/leaves",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1360,
            icon: <TableCellsIcon {...icon} />,
            name: "Overtime",
            path: "/tables/overtime",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1370,
            icon: <TableCellsIcon {...icon} />,
            name: "Official Business Trip",
            path: "/tables/offical-business-trip",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1380,
            icon: <TableCellsIcon {...icon} />,
            name: "U.A",
            path: "/tables/unaccounted-attendance",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1390,
            icon: <TableCellsIcon {...icon} />,
            name: "Maternity",
            path: "/tables/maternity",
            element: <Tables />,
            hasSubItems: false,
          },
        ]
      },
      {
        id: 1400,
        icon: <BellIcon {...icon} />,
        name: "Reports",
        path: "/notifactions",
        element: <Notifications />,
        hasSubItems: false,
      },
      {
        id: 1500,
        icon: <TableCellsIcon {...icon} />,
        name: "Forms",
        path: "/forms",
        element: <Tables />,
        hasSubItems: true,
        subItems: [
          {
            id: 1510,
            icon: <TableCellsIcon {...icon} />,
            name: "COE",
            path: "/forms/coe",
            element: <Tables />,
            hasSubItems: false,
          },
        ]
      },
      {
        id: 1600,
        icon: <DocumentIcon {...icon} />,
        name: "Payroll",
        path: "/payroll",
        element: <Tables />,
        hasSubItems: true,
        subItems: [
          {
            id: 1610,
            icon: <DocumentIcon {...icon} />,
            name: "Payroll Register",
            path: "/payroll/payroll-register",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1620,
            icon: <DocumentIcon {...icon} />,
            name: "Print Payslip",
            path: "/payroll/print-payslip",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1630,
            icon: <DocumentIcon {...icon} />,
            name: "Bonus",
            path: "/payroll/bonus",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1640,
            icon: <DocumentIcon {...icon} />,
            name: "13th Month",
            path: "/payroll/13th-month",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1650,
            icon: <DocumentIcon {...icon} />,
            name: "Compensation",
            path: "/payroll/compensation",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1660,
            icon: <DocumentIcon {...icon} />,
            name: "Adjustment Others",
            path: "/payroll/adjustment-others",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1670,
            icon: <DocumentIcon {...icon} />,
            name: "Tax Refund",
            path: "/payroll/tax-refund",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1680,
            icon: <DocumentIcon {...icon} />,
            name: "Government Deduction",
            path: "/payroll/government-deduction",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1690,
            icon: <DocumentIcon {...icon} />,
            name: "Other Deduction",
            path: "/payroll/other-deduction",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1691,
            icon: <DocumentIcon {...icon} />,
            name: "SSS Loan",
            path: "/payroll/sss-loan",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1692,
            icon: <DocumentIcon {...icon} />,
            name: "Payroll Summary",
            path: "/payroll/payroll-summary",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1693,
            icon: <TableCellsIcon {...icon} />,
            name: "Net Pay Bank Summary",
            path: "/payroll/net-pay-bank-summary",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1694,
            icon: <TableCellsIcon {...icon} />,
            name: "Allowance Summary",
            path: "/payroll/allowance-summary",
            element: <Tables />,
            hasSubItems: false,
          },
          {
            id: 1695,
            icon: <TableCellsIcon {...icon} />,
            name: "Alpha List",
            path: "/payroll/alpha-list",
            element: <Tables />,
            hasSubItems: false,
          },
        ]
      },
      {
        id: 1700,
        icon: <SpeakerWaveIcon {...icon} />,
        name: "Announcement",
        path: "/announcements",
        element: <Tables />,
        hasSubItems: true,
        subItems: [
          {
            id: 1710,
            icon: <SpeakerWaveIcon {...icon} />,
            name: "Post Announcements",
            path: "/announcements/post-announcements",
            element: <Tables />,
            hasSubItems: false,
          },
        ]
      },
      {
        id: 1800,
        icon: <QuestionMarkCircleIcon {...icon} />,
        name: "Help",
        path: "/help",
        element: <Tables />,
        hasSubItems: false,
      },
    ],
  },

  // {
  //   // title: "auth pages",
  //   id: 2000,
  //   layout: "auth",
  //   pages: [
  //     {
  //       id: 2100,
  //       icon: <ArrowRightOnRectangleIcon {...icon} />,
  //       name: "sign in",
  //       path: "/sign-in",
  //       element: <SignIn />,
  //       hasSubItems: false,
  //     },
  //     {
  //       id: 2200,
  //       icon: <UserPlusIcon {...icon} />,
  //       name: "sign up",
  //       path: "/sign-up",
  //       element: <SignUp />,
  //       hasSubItems: false,
  //     },
  //   ],
  // },
];

export default routes;
